import os
import re
import random
import hashlib
import hmac
import urllib2
import json
import pdb
import logging
import random, string
from string import letters
import csv
import datetime

import webapp2
import jinja2
import cgi
from time import sleep
from google.appengine.ext.webapp.util import run_wsgi_app
from datetime import datetime, date, time

from google.appengine.ext import db
from google.appengine.ext import blobstore
from google.appengine.ext.webapp import blobstore_handlers
from google.appengine.ext.db import GqlQuery
from google.appengine.api import mail
from politics import *

#---------------------------User Implementation Functions--------------------------
def make_secure_val(val):
    return '%s|%s' % (val, hmac.new(secret, val).hexdigest())

def check_secure_val(secure_val):
    val = secure_val.split('|')[0]
    if secure_val == make_secure_val(val):
        return val

def make_salt(length = 30):
    random_bytes = os.urandom(length+2)
    token = base64.urlsafe_b64encode(random_bytes).decode('utf-8')
    reset_key = token[:-2]
    logging.error(reset_key)
    return reset_key

def make_pw_hash(username, pw, salt = None):
    if not salt:
        salt = make_salt()
    h = hashlib.sha256(username + pw + salt).hexdigest()
    return '%s,%s' % (salt, h)

def valid_pw(name, password, h):
    salt = h.split(',')[0]
    return h == make_pw_hash(name, password, salt)

#-------------------------Database Classes------------------------------
class User(db.Model):
    firstname = db.StringProperty()
    lastname = db.StringProperty()
    username = db.StringProperty(required = True)
    email = db.StringProperty(required = True)
    pw_hash = db.StringProperty(required = True)
    emailverified = db.BooleanProperty()
    district = db.StringProperty()
    age = db.IntegerProperty()
    gender = db.StringProperty()
    created = db.DateTimeProperty(required = True, auto_now = True)
    last_modified = db.DateTimeProperty(required = True, auto_now = True)
    reset_code = db.StringProperty()
    reset_expr = db.DateTimeProperty()

    @classmethod
    def by_id(cls, uid):
        return User.get_by_id(uid)

    @classmethod
    def by_email(cls, email):
        u = cls.all().filter('email =', email).get()
        return u

    @classmethod
    def by_username(cls, username):
        u = cls.all().filter('username =', username).get()
        return u

    @classmethod
    def register(cls, username, email, pw, fname, lname):
        pw_hash = make_pw_hash(username, pw)
        return cls( username = username,
                    email = email,
                    pw_hash = pw_hash,
                    firstname = fname,
                    lastname = lname)

    @classmethod
    def login(cls, username, pw):
        u = cls.by_username(username)
        if u and valid_pw(username, pw, u.pw_hash):
            return u

    @classmethod
    def changepass(cls, username, pw):
        pw_hash = make_pw_hash(username, pw)
        return cls( username = 'NONE',
                    email = 'NONE',
                    pw_hash = pw_hash)

class Cookie_Info(db.Model):
    times_visit = db.IntegerProperty(required = True)
    signup = db.BooleanProperty(required = True)

class Feed_Radio_Buttons(db.Model):
    cookie_id = db.IntegerProperty(required = True)
    origin_val = db.IntegerProperty()
    return_val = db.IntegerProperty()
    recomm_val = db.IntegerProperty()

class Feed_Top_Issues(db.Model):
    cookie_id = db.IntegerProperty(required = True)
    envir_sci = db.IntegerProperty()
    crim_just = db.IntegerProperty()
    health = db.IntegerProperty()
    privacy = db.IntegerProperty()
    edu = db.IntegerProperty()
    camp_fin_lobby = db.IntegerProperty()
    soc_issues = db.IntegerProperty()
    gun_cont = db.IntegerProperty()
    immig = db.IntegerProperty()
    econ = db.IntegerProperty()
    for_pol = db.IntegerProperty()
    terror = db.IntegerProperty()

class State(db.Model):
    name = db.StringProperty(required = True)
    abbreviation = db.StringProperty(required = True)
    num_reps = db.IntegerProperty()
    ge_delegates = db.IntegerProperty()
    primary_type = db.StringProperty()
    primary_notes = db.StringProperty()
    registration_link = db.StringProperty()
    D_primary_date = db.DateTimeProperty()
    D_delegates = db.IntegerProperty()
    D_pledged = db.IntegerProperty()
    D_superdelegates = db.IntegerProperty()
    R_primary_date = db.DateTimeProperty()
    R_delegates = db.IntegerProperty()

class Candidate(db.Model):
    name = db.StringProperty(required = True)
    party = db.StringProperty(required = True)
    delegates = db.IntegerProperty()
    superdelegates = db.IntegerProperty()

class Votes(db.Model):
    bill_id = db.StringProperty(required = True)
    rid = db.StringProperty(required = True)
    congress = db.StringProperty(required = True)
    voted_at = db.StringProperty(required = True)
    vote_type = db.StringProperty(required = True)
    roll_type = db.StringProperty(required = True)
    question = db.StringProperty(required = True)
    required = db.StringProperty(required = True)
    result = db.StringProperty(required = True)
    source = db.StringProperty(required = True)
    breakdown = db.StringProperty(required = True)
    break_gop = db.StringProperty(required = True)
    break_dem = db.StringProperty(required = True)
    break_ind = db.StringProperty(required = True)

class Ind_Votes(db.Model):
    bill_id = db.StringProperty(required = True)
    roll_id = db.StringProperty(required = True)
    A000022 = db.StringProperty(required = False)
    A000055 = db.StringProperty(required = False)
    A000069 = db.StringProperty(required = False)
    A000210 = db.StringProperty(required = False)
    A000358 = db.StringProperty(required = False)
    A000360 = db.StringProperty(required = False)
    A000361 = db.StringProperty(required = False)
    A000362 = db.StringProperty(required = False)
    A000365 = db.StringProperty(required = False)
    A000366 = db.StringProperty(required = False)
    A000367 = db.StringProperty(required = False)
    A000368 = db.StringProperty(required = False)
    A000369 = db.StringProperty(required = False)
    A000370 = db.StringProperty(required = False)
    A000371 = db.StringProperty(required = False)
    A000372 = db.StringProperty(required = False)
    A000373 = db.StringProperty(required = False)
    A000374 = db.StringProperty(required = False)
    B000013 = db.StringProperty(required = False)
    B000208 = db.StringProperty(required = False)
    B000213 = db.StringProperty(required = False)
    B000220 = db.StringProperty(required = False)
    B000243 = db.StringProperty(required = False)
    B000287 = db.StringProperty(required = False)
    B000410 = db.StringProperty(required = False)
    B000461 = db.StringProperty(required = False)
    B000468 = db.StringProperty(required = False)
    B000490 = db.StringProperty(required = False)
    B000574 = db.StringProperty(required = False)
    B000575 = db.StringProperty(required = False)
    B000589 = db.StringProperty(required = False)
    B000652 = db.StringProperty(required = False)
    B000711 = db.StringProperty(required = False)
    B000755 = db.StringProperty(required = False)
    B000911 = db.StringProperty(required = False)
    B000944 = db.StringProperty(required = False)
    B001135 = db.StringProperty(required = False)
    B001149 = db.StringProperty(required = False)
    B001227 = db.StringProperty(required = False)
    B001228 = db.StringProperty(required = False)
    B001230 = db.StringProperty(required = False)
    B001231 = db.StringProperty(required = False)
    B001232 = db.StringProperty(required = False)
    B001234 = db.StringProperty(required = False)
    B001236 = db.StringProperty(required = False)
    B001242 = db.StringProperty(required = False)
    B001243 = db.StringProperty(required = False)
    B001244 = db.StringProperty(required = False)
    B001245 = db.StringProperty(required = False)
    B001248 = db.StringProperty(required = False)
    B001250 = db.StringProperty(required = False)
    B001251 = db.StringProperty(required = False)
    B001252 = db.StringProperty(required = False)
    B001254 = db.StringProperty(required = False)
    B001255 = db.StringProperty(required = False)
    B001256 = db.StringProperty(required = False)
    B001257 = db.StringProperty(required = False)
    B001259 = db.StringProperty(required = False)
    B001260 = db.StringProperty(required = False)
    B001261 = db.StringProperty(required = False)
    B001262 = db.StringProperty(required = False)
    B001265 = db.StringProperty(required = False)
    B001267 = db.StringProperty(required = False)
    B001268 = db.StringProperty(required = False)
    B001269 = db.StringProperty(required = False)
    B001270 = db.StringProperty(required = False)
    B001271 = db.StringProperty(required = False)
    B001272 = db.StringProperty(required = False)
    B001273 = db.StringProperty(required = False)
    B001274 = db.StringProperty(required = False)
    B001275 = db.StringProperty(required = False)
    B001276 = db.StringProperty(required = False)
    B001277 = db.StringProperty(required = False)
    B001278 = db.StringProperty(required = False)
    B001279 = db.StringProperty(required = False)
    B001280 = db.StringProperty(required = False)
    B001281 = db.StringProperty(required = False)
    B001282 = db.StringProperty(required = False)
    B001283 = db.StringProperty(required = False)
    B001284 = db.StringProperty(required = False)
    B001285 = db.StringProperty(required = False)
    B001286 = db.StringProperty(required = False)
    B001287 = db.StringProperty(required = False)
    B001288 = db.StringProperty(required = False)
    B001289 = db.StringProperty(required = False)
    B001290 = db.StringProperty(required = False)
    B001291 = db.StringProperty(required = False)
    B001292 = db.StringProperty(required = False)
    B001293 = db.StringProperty(required = False)
    B001294 = db.StringProperty(required = False)
    B001295 = db.StringProperty(required = False)
    B001296 = db.StringProperty(required = False)
    B001297 = db.StringProperty(required = False)
    C000059 = db.StringProperty(required = False)
    C000071 = db.StringProperty(required = False)
    C000127 = db.StringProperty(required = False)
    C000141 = db.StringProperty(required = False)
    C000174 = db.StringProperty(required = False)
    C000266 = db.StringProperty(required = False)
    C000286 = db.StringProperty(required = False)
    C000380 = db.StringProperty(required = False)
    C000537 = db.StringProperty(required = False)
    C000542 = db.StringProperty(required = False)
    C000556 = db.StringProperty(required = False)
    C000560 = db.StringProperty(required = False)
    C000567 = db.StringProperty(required = False)
    C000705 = db.StringProperty(required = False)
    C000714 = db.StringProperty(required = False)
    C000754 = db.StringProperty(required = False)
    C000794 = db.StringProperty(required = False)
    C000880 = db.StringProperty(required = False)
    C000984 = db.StringProperty(required = False)
    C001035 = db.StringProperty(required = False)
    C001036 = db.StringProperty(required = False)
    C001037 = db.StringProperty(required = False)
    C001038 = db.StringProperty(required = False)
    C001045 = db.StringProperty(required = False)
    C001046 = db.StringProperty(required = False)
    C001047 = db.StringProperty(required = False)
    C001048 = db.StringProperty(required = False)
    C001049 = db.StringProperty(required = False)
    C001050 = db.StringProperty(required = False)
    C001051 = db.StringProperty(required = False)
    C001053 = db.StringProperty(required = False)
    C001056 = db.StringProperty(required = False)
    C001058 = db.StringProperty(required = False)
    C001059 = db.StringProperty(required = False)
    C001060 = db.StringProperty(required = False)
    C001061 = db.StringProperty(required = False)
    C001062 = db.StringProperty(required = False)
    C001063 = db.StringProperty(required = False)
    C001064 = db.StringProperty(required = False)
    C001066 = db.StringProperty(required = False)
    C001067 = db.StringProperty(required = False)
    C001068 = db.StringProperty(required = False)
    C001069 = db.StringProperty(required = False)
    C001070 = db.StringProperty(required = False)
    C001071 = db.StringProperty(required = False)
    C001072 = db.StringProperty(required = False)
    C001075 = db.StringProperty(required = False)
    C001076 = db.StringProperty(required = False)
    C001077 = db.StringProperty(required = False)
    C001078 = db.StringProperty(required = False)
    C001080 = db.StringProperty(required = False)
    C001081 = db.StringProperty(required = False)
    C001082 = db.StringProperty(required = False)
    C001083 = db.StringProperty(required = False)
    C001084 = db.StringProperty(required = False)
    C001085 = db.StringProperty(required = False)
    C001086 = db.StringProperty(required = False)
    C001087 = db.StringProperty(required = False)
    C001088 = db.StringProperty(required = False)
    C001089 = db.StringProperty(required = False)
    C001090 = db.StringProperty(required = False)
    C001091 = db.StringProperty(required = False)
    C001092 = db.StringProperty(required = False)
    C001093 = db.StringProperty(required = False)
    C001094 = db.StringProperty(required = False)
    C001095 = db.StringProperty(required = False)
    C001096 = db.StringProperty(required = False)
    C001097 = db.StringProperty(required = False)
    C001098 = db.StringProperty(required = False)
    C001101 = db.StringProperty(required = False)
    C001102 = db.StringProperty(required = False)
    C001103 = db.StringProperty(required = False)
    C001105 = db.StringProperty(required = False)
    C001106 = db.StringProperty(required = False)
    C001107 = db.StringProperty(required = False)
    D000096 = db.StringProperty(required = False)
    D000191 = db.StringProperty(required = False)
    D000197 = db.StringProperty(required = False)
    D000216 = db.StringProperty(required = False)
    D000327 = db.StringProperty(required = False)
    D000355 = db.StringProperty(required = False)
    D000399 = db.StringProperty(required = False)
    D000482 = db.StringProperty(required = False)
    D000492 = db.StringProperty(required = False)
    D000533 = db.StringProperty(required = False)
    D000563 = db.StringProperty(required = False)
    D000595 = db.StringProperty(required = False)
    D000598 = db.StringProperty(required = False)
    D000600 = db.StringProperty(required = False)
    D000604 = db.StringProperty(required = False)
    D000607 = db.StringProperty(required = False)
    D000610 = db.StringProperty(required = False)
    D000612 = db.StringProperty(required = False)
    D000613 = db.StringProperty(required = False)
    D000614 = db.StringProperty(required = False)
    D000615 = db.StringProperty(required = False)
    D000616 = db.StringProperty(required = False)
    D000617 = db.StringProperty(required = False)
    D000618 = db.StringProperty(required = False)
    D000619 = db.StringProperty(required = False)
    D000620 = db.StringProperty(required = False)
    D000621 = db.StringProperty(required = False)
    D000622 = db.StringProperty(required = False)
    D000623 = db.StringProperty(required = False)
    D000624 = db.StringProperty(required = False)
    D000625 = db.StringProperty(required = False)
    E000172 = db.StringProperty(required = False)
    E000179 = db.StringProperty(required = False)
    E000215 = db.StringProperty(required = False)
    E000285 = db.StringProperty(required = False)
    E000288 = db.StringProperty(required = False)
    E000290 = db.StringProperty(required = False)
    E000291 = db.StringProperty(required = False)
    E000292 = db.StringProperty(required = False)
    E000293 = db.StringProperty(required = False)
    E000294 = db.StringProperty(required = False)
    E000295 = db.StringProperty(required = False)
    F000010 = db.StringProperty(required = False)
    F000030 = db.StringProperty(required = False)
    F000043 = db.StringProperty(required = False)
    F000062 = db.StringProperty(required = False)
    F000116 = db.StringProperty(required = False)
    F000339 = db.StringProperty(required = False)
    F000372 = db.StringProperty(required = False)
    F000444 = db.StringProperty(required = False)
    F000445 = db.StringProperty(required = False)
    F000448 = db.StringProperty(required = False)
    F000449 = db.StringProperty(required = False)
    F000450 = db.StringProperty(required = False)
    F000451 = db.StringProperty(required = False)
    F000454 = db.StringProperty(required = False)
    F000455 = db.StringProperty(required = False)
    F000456 = db.StringProperty(required = False)
    F000457 = db.StringProperty(required = False)
    F000458 = db.StringProperty(required = False)
    F000459 = db.StringProperty(required = False)
    F000460 = db.StringProperty(required = False)
    F000461 = db.StringProperty(required = False)
    F000462 = db.StringProperty(required = False)
    F000463 = db.StringProperty(required = False)
    G000021 = db.StringProperty(required = False)
    G000289 = db.StringProperty(required = False)
    G000359 = db.StringProperty(required = False)
    G000377 = db.StringProperty(required = False)
    G000386 = db.StringProperty(required = False)
    G000410 = db.StringProperty(required = False)
    G000535 = db.StringProperty(required = False)
    G000544 = db.StringProperty(required = False)
    G000546 = db.StringProperty(required = False)
    G000548 = db.StringProperty(required = False)
    G000549 = db.StringProperty(required = False)
    G000550 = db.StringProperty(required = False)
    G000551 = db.StringProperty(required = False)
    G000552 = db.StringProperty(required = False)
    G000553 = db.StringProperty(required = False)
    G000555 = db.StringProperty(required = False)
    G000556 = db.StringProperty(required = False)
    G000558 = db.StringProperty(required = False)
    G000559 = db.StringProperty(required = False)
    G000560 = db.StringProperty(required = False)
    G000562 = db.StringProperty(required = False)
    G000563 = db.StringProperty(required = False)
    G000564 = db.StringProperty(required = False)
    G000565 = db.StringProperty(required = False)
    G000566 = db.StringProperty(required = False)
    G000567 = db.StringProperty(required = False)
    G000568 = db.StringProperty(required = False)
    G000569 = db.StringProperty(required = False)
    G000570 = db.StringProperty(required = False)
    G000571 = db.StringProperty(required = False)
    G000572 = db.StringProperty(required = False)
    G000573 = db.StringProperty(required = False)
    G000574 = db.StringProperty(required = False)
    G000575 = db.StringProperty(required = False)
    G000576 = db.StringProperty(required = False)
    G000577 = db.StringProperty(required = False)
    H000067 = db.StringProperty(required = False)
    H000206 = db.StringProperty(required = False)
    H000324 = db.StringProperty(required = False)
    H000329 = db.StringProperty(required = False)
    H000338 = db.StringProperty(required = False)
    H000528 = db.StringProperty(required = False)
    H000627 = db.StringProperty(required = False)
    H000636 = db.StringProperty(required = False)
    H000712 = db.StringProperty(required = False)
    H000874 = db.StringProperty(required = False)
    H001016 = db.StringProperty(required = False)
    H001032 = db.StringProperty(required = False)
    H001034 = db.StringProperty(required = False)
    H001036 = db.StringProperty(required = False)
    H001038 = db.StringProperty(required = False)
    H001041 = db.StringProperty(required = False)
    H001042 = db.StringProperty(required = False)
    H001045 = db.StringProperty(required = False)
    H001046 = db.StringProperty(required = False)
    H001047 = db.StringProperty(required = False)
    H001048 = db.StringProperty(required = False)
    H001049 = db.StringProperty(required = False)
    H001050 = db.StringProperty(required = False)
    H001051 = db.StringProperty(required = False)
    H001052 = db.StringProperty(required = False)
    H001053 = db.StringProperty(required = False)
    H001054 = db.StringProperty(required = False)
    H001055 = db.StringProperty(required = False)
    H001056 = db.StringProperty(required = False)
    H001057 = db.StringProperty(required = False)
    H001058 = db.StringProperty(required = False)
    H001059 = db.StringProperty(required = False)
    H001060 = db.StringProperty(required = False)
    H001061 = db.StringProperty(required = False)
    H001062 = db.StringProperty(required = False)
    H001063 = db.StringProperty(required = False)
    H001064 = db.StringProperty(required = False)
    H001065 = db.StringProperty(required = False)
    H001066 = db.StringProperty(required = False)
    H001067 = db.StringProperty(required = False)
    H001068 = db.StringProperty(required = False)
    H001069 = db.StringProperty(required = False)
    H001070 = db.StringProperty(required = False)
    H001071 = db.StringProperty(required = False)
    H001072 = db.StringProperty(required = False)
    H001073 = db.StringProperty(required = False)
    I000024 = db.StringProperty(required = False)
    I000055 = db.StringProperty(required = False)
    I000056 = db.StringProperty(required = False)
    I000057 = db.StringProperty(required = False)
    J000032 = db.StringProperty(required = False)
    J000126 = db.StringProperty(required = False)
    J000174 = db.StringProperty(required = False)
    J000177 = db.StringProperty(required = False)
    J000255 = db.StringProperty(required = False)
    J000283 = db.StringProperty(required = False)
    J000285 = db.StringProperty(required = False)
    J000288 = db.StringProperty(required = False)
    J000289 = db.StringProperty(required = False)
    J000290 = db.StringProperty(required = False)
    J000291 = db.StringProperty(required = False)
    J000292 = db.StringProperty(required = False)
    J000293 = db.StringProperty(required = False)
    J000294 = db.StringProperty(required = False)
    J000295 = db.StringProperty(required = False)
    J000296 = db.StringProperty(required = False)
    J000297 = db.StringProperty(required = False)
    K000009 = db.StringProperty(required = False)
    K000148 = db.StringProperty(required = False)
    K000172 = db.StringProperty(required = False)
    K000188 = db.StringProperty(required = False)
    K000210 = db.StringProperty(required = False)
    K000220 = db.StringProperty(required = False)
    K000305 = db.StringProperty(required = False)
    K000336 = db.StringProperty(required = False)
    K000352 = db.StringProperty(required = False)
    K000360 = db.StringProperty(required = False)
    K000362 = db.StringProperty(required = False)
    K000363 = db.StringProperty(required = False)
    K000367 = db.StringProperty(required = False)
    K000368 = db.StringProperty(required = False)
    K000369 = db.StringProperty(required = False)
    K000375 = db.StringProperty(required = False)
    K000376 = db.StringProperty(required = False)
    K000378 = db.StringProperty(required = False)
    K000379 = db.StringProperty(required = False)
    K000380 = db.StringProperty(required = False)
    K000381 = db.StringProperty(required = False)
    K000382 = db.StringProperty(required = False)
    K000383 = db.StringProperty(required = False)
    K000384 = db.StringProperty(required = False)
    K000385 = db.StringProperty(required = False)
    K000386 = db.StringProperty(required = False)
    K000387 = db.StringProperty(required = False)
    K000388 = db.StringProperty(required = False)
    L000111 = db.StringProperty(required = False)
    L000123 = db.StringProperty(required = False)
    L000174 = db.StringProperty(required = False)
    L000261 = db.StringProperty(required = False)
    L000263 = db.StringProperty(required = False)
    L000274 = db.StringProperty(required = False)
    L000287 = db.StringProperty(required = False)
    L000304 = db.StringProperty(required = False)
    L000397 = db.StringProperty(required = False)
    L000480 = db.StringProperty(required = False)
    L000491 = db.StringProperty(required = False)
    L000504 = db.StringProperty(required = False)
    L000517 = db.StringProperty(required = False)
    L000550 = db.StringProperty(required = False)
    L000551 = db.StringProperty(required = False)
    L000553 = db.StringProperty(required = False)
    L000554 = db.StringProperty(required = False)
    L000557 = db.StringProperty(required = False)
    L000559 = db.StringProperty(required = False)
    L000560 = db.StringProperty(required = False)
    L000562 = db.StringProperty(required = False)
    L000563 = db.StringProperty(required = False)
    L000564 = db.StringProperty(required = False)
    L000565 = db.StringProperty(required = False)
    L000566 = db.StringProperty(required = False)
    L000567 = db.StringProperty(required = False)
    L000569 = db.StringProperty(required = False)
    L000570 = db.StringProperty(required = False)
    L000571 = db.StringProperty(required = False)
    L000573 = db.StringProperty(required = False)
    L000574 = db.StringProperty(required = False)
    L000575 = db.StringProperty(required = False)
    L000576 = db.StringProperty(required = False)
    L000577 = db.StringProperty(required = False)
    L000578 = db.StringProperty(required = False)
    L000579 = db.StringProperty(required = False)
    L000580 = db.StringProperty(required = False)
    L000581 = db.StringProperty(required = False)
    L000582 = db.StringProperty(required = False)
    L000583 = db.StringProperty(required = False)
    L000584 = db.StringProperty(required = False)
    L000585 = db.StringProperty(required = False)
    M000087 = db.StringProperty(required = False)
    M000133 = db.StringProperty(required = False)
    M000303 = db.StringProperty(required = False)
    M000309 = db.StringProperty(required = False)
    M000312 = db.StringProperty(required = False)
    M000355 = db.StringProperty(required = False)
    M000404 = db.StringProperty(required = False)
    M000485 = db.StringProperty(required = False)
    M000508 = db.StringProperty(required = False)
    M000639 = db.StringProperty(required = False)
    M000689 = db.StringProperty(required = False)
    M000702 = db.StringProperty(required = False)
    M000725 = db.StringProperty(required = False)
    M000933 = db.StringProperty(required = False)
    M000934 = db.StringProperty(required = False)
    M001111 = db.StringProperty(required = False)
    M001134 = db.StringProperty(required = False)
    M001137 = db.StringProperty(required = False)
    M001138 = db.StringProperty(required = False)
    M001139 = db.StringProperty(required = False)
    M001142 = db.StringProperty(required = False)
    M001143 = db.StringProperty(required = False)
    M001144 = db.StringProperty(required = False)
    M001149 = db.StringProperty(required = False)
    M001150 = db.StringProperty(required = False)
    M001151 = db.StringProperty(required = False)
    M001153 = db.StringProperty(required = False)
    M001154 = db.StringProperty(required = False)
    M001155 = db.StringProperty(required = False)
    M001156 = db.StringProperty(required = False)
    M001157 = db.StringProperty(required = False)
    M001158 = db.StringProperty(required = False)
    M001159 = db.StringProperty(required = False)
    M001160 = db.StringProperty(required = False)
    M001163 = db.StringProperty(required = False)
    M001165 = db.StringProperty(required = False)
    M001166 = db.StringProperty(required = False)
    M001169 = db.StringProperty(required = False)
    M001170 = db.StringProperty(required = False)
    M001171 = db.StringProperty(required = False)
    M001176 = db.StringProperty(required = False)
    M001177 = db.StringProperty(required = False)
    M001179 = db.StringProperty(required = False)
    M001180 = db.StringProperty(required = False)
    M001181 = db.StringProperty(required = False)
    M001182 = db.StringProperty(required = False)
    M001183 = db.StringProperty(required = False)
    M001184 = db.StringProperty(required = False)
    M001185 = db.StringProperty(required = False)
    M001187 = db.StringProperty(required = False)
    M001188 = db.StringProperty(required = False)
    M001189 = db.StringProperty(required = False)
    M001190 = db.StringProperty(required = False)
    M001191 = db.StringProperty(required = False)
    M001192 = db.StringProperty(required = False)
    M001193 = db.StringProperty(required = False)
    M001194 = db.StringProperty(required = False)
    M001195 = db.StringProperty(required = False)
    M001196 = db.StringProperty(required = False)
    M001197 = db.StringProperty(required = False)
    N000002 = db.StringProperty(required = False)
    N000015 = db.StringProperty(required = False)
    N000032 = db.StringProperty(required = False)
    N000127 = db.StringProperty(required = False)
    N000147 = db.StringProperty(required = False)
    N000179 = db.StringProperty(required = False)
    N000180 = db.StringProperty(required = False)
    N000181 = db.StringProperty(required = False)
    N000182 = db.StringProperty(required = False)
    N000184 = db.StringProperty(required = False)
    N000185 = db.StringProperty(required = False)
    N000186 = db.StringProperty(required = False)
    N000187 = db.StringProperty(required = False)
    N000188 = db.StringProperty(required = False)
    N000189 = db.StringProperty(required = False)
    O000085 = db.StringProperty(required = False)
    O000168 = db.StringProperty(required = False)
    O000169 = db.StringProperty(required = False)
    O000170 = db.StringProperty(required = False)
    P000034 = db.StringProperty(required = False)
    P000096 = db.StringProperty(required = False)
    P000099 = db.StringProperty(required = False)
    P000197 = db.StringProperty(required = False)
    P000258 = db.StringProperty(required = False)
    P000265 = db.StringProperty(required = False)
    P000373 = db.StringProperty(required = False)
    P000449 = db.StringProperty(required = False)
    P000523 = db.StringProperty(required = False)
    P000583 = db.StringProperty(required = False)
    P000585 = db.StringProperty(required = False)
    P000587 = db.StringProperty(required = False)
    P000588 = db.StringProperty(required = False)
    P000590 = db.StringProperty(required = False)
    P000591 = db.StringProperty(required = False)
    P000592 = db.StringProperty(required = False)
    P000593 = db.StringProperty(required = False)
    P000594 = db.StringProperty(required = False)
    P000595 = db.StringProperty(required = False)
    P000596 = db.StringProperty(required = False)
    P000597 = db.StringProperty(required = False)
    P000598 = db.StringProperty(required = False)
    P000599 = db.StringProperty(required = False)
    P000601 = db.StringProperty(required = False)
    P000602 = db.StringProperty(required = False)
    P000603 = db.StringProperty(required = False)
    P000604 = db.StringProperty(required = False)
    P000605 = db.StringProperty(required = False)
    P000606 = db.StringProperty(required = False)
    P000607 = db.StringProperty(required = False)
    P000608 = db.StringProperty(required = False)
    P000609 = db.StringProperty(required = False)
    P000610 = db.StringProperty(required = False)
    P000611 = db.StringProperty(required = False)
    P000612 = db.StringProperty(required = False)
    Q000023 = db.StringProperty(required = False)
    Q000024 = db.StringProperty(required = False)
    R000011 = db.StringProperty(required = False)
    R000053 = db.StringProperty(required = False)
    R000122 = db.StringProperty(required = False)
    R000146 = db.StringProperty(required = False)
    R000170 = db.StringProperty(required = False)
    R000307 = db.StringProperty(required = False)
    R000361 = db.StringProperty(required = False)
    R000395 = db.StringProperty(required = False)
    R000409 = db.StringProperty(required = False)
    R000435 = db.StringProperty(required = False)
    R000462 = db.StringProperty(required = False)
    R000486 = db.StringProperty(required = False)
    R000487 = db.StringProperty(required = False)
    R000515 = db.StringProperty(required = False)
    R000570 = db.StringProperty(required = False)
    R000571 = db.StringProperty(required = False)
    R000572 = db.StringProperty(required = False)
    R000573 = db.StringProperty(required = False)
    R000575 = db.StringProperty(required = False)
    R000576 = db.StringProperty(required = False)
    R000577 = db.StringProperty(required = False)
    R000578 = db.StringProperty(required = False)
    R000580 = db.StringProperty(required = False)
    R000581 = db.StringProperty(required = False)
    R000582 = db.StringProperty(required = False)
    R000583 = db.StringProperty(required = False)
    R000584 = db.StringProperty(required = False)
    R000585 = db.StringProperty(required = False)
    R000586 = db.StringProperty(required = False)
    R000587 = db.StringProperty(required = False)
    R000588 = db.StringProperty(required = False)
    R000589 = db.StringProperty(required = False)
    R000590 = db.StringProperty(required = False)
    R000591 = db.StringProperty(required = False)
    R000592 = db.StringProperty(required = False)
    R000593 = db.StringProperty(required = False)
    R000594 = db.StringProperty(required = False)
    R000595 = db.StringProperty(required = False)
    R000597 = db.StringProperty(required = False)
    R000598 = db.StringProperty(required = False)
    R000599 = db.StringProperty(required = False)
    R000600 = db.StringProperty(required = False)
    R000601 = db.StringProperty(required = False)
    R000602 = db.StringProperty(required = False)
    R000603 = db.StringProperty(required = False)
    R000604 = db.StringProperty(required = False)
    R000605 = db.StringProperty(required = False)
    S000018 = db.StringProperty(required = False)
    S000030 = db.StringProperty(required = False)
    S000033 = db.StringProperty(required = False)
    S000051 = db.StringProperty(required = False)
    S000148 = db.StringProperty(required = False)
    S000185 = db.StringProperty(required = False)
    S000244 = db.StringProperty(required = False)
    S000248 = db.StringProperty(required = False)
    S000250 = db.StringProperty(required = False)
    S000320 = db.StringProperty(required = False)
    S000344 = db.StringProperty(required = False)
    S000364 = db.StringProperty(required = False)
    S000480 = db.StringProperty(required = False)
    S000510 = db.StringProperty(required = False)
    S000522 = db.StringProperty(required = False)
    S000583 = db.StringProperty(required = False)
    S000663 = db.StringProperty(required = False)
    S000770 = db.StringProperty(required = False)
    S000810 = db.StringProperty(required = False)
    S000822 = db.StringProperty(required = False)
    S000937 = db.StringProperty(required = False)
    S001141 = db.StringProperty(required = False)
    S001145 = db.StringProperty(required = False)
    S001148 = db.StringProperty(required = False)
    S001150 = db.StringProperty(required = False)
    S001154 = db.StringProperty(required = False)
    S001155 = db.StringProperty(required = False)
    S001156 = db.StringProperty(required = False)
    S001157 = db.StringProperty(required = False)
    S001162 = db.StringProperty(required = False)
    S001164 = db.StringProperty(required = False)
    S001165 = db.StringProperty(required = False)
    S001168 = db.StringProperty(required = False)
    S001170 = db.StringProperty(required = False)
    S001171 = db.StringProperty(required = False)
    S001172 = db.StringProperty(required = False)
    S001174 = db.StringProperty(required = False)
    S001175 = db.StringProperty(required = False)
    S001176 = db.StringProperty(required = False)
    S001177 = db.StringProperty(required = False)
    S001179 = db.StringProperty(required = False)
    S001180 = db.StringProperty(required = False)
    S001181 = db.StringProperty(required = False)
    S001182 = db.StringProperty(required = False)
    S001183 = db.StringProperty(required = False)
    S001184 = db.StringProperty(required = False)
    S001185 = db.StringProperty(required = False)
    S001186 = db.StringProperty(required = False)
    S001187 = db.StringProperty(required = False)
    S001188 = db.StringProperty(required = False)
    S001189 = db.StringProperty(required = False)
    S001190 = db.StringProperty(required = False)
    S001191 = db.StringProperty(required = False)
    S001192 = db.StringProperty(required = False)
    S001193 = db.StringProperty(required = False)
    S001194 = db.StringProperty(required = False)
    S001195 = db.StringProperty(required = False)
    S001196 = db.StringProperty(required = False)
    S001197 = db.StringProperty(required = False)
    S001198 = db.StringProperty(required = False)
    T000193 = db.StringProperty(required = False)
    T000238 = db.StringProperty(required = False)
    T000250 = db.StringProperty(required = False)
    T000266 = db.StringProperty(required = False)
    T000326 = db.StringProperty(required = False)
    T000459 = db.StringProperty(required = False)
    T000460 = db.StringProperty(required = False)
    T000461 = db.StringProperty(required = False)
    T000462 = db.StringProperty(required = False)
    T000463 = db.StringProperty(required = False)
    T000464 = db.StringProperty(required = False)
    T000465 = db.StringProperty(required = False)
    T000467 = db.StringProperty(required = False)
    T000468 = db.StringProperty(required = False)
    T000469 = db.StringProperty(required = False)
    T000470 = db.StringProperty(required = False)
    T000471 = db.StringProperty(required = False)
    T000472 = db.StringProperty(required = False)
    T000473 = db.StringProperty(required = False)
    T000474 = db.StringProperty(required = False)
    T000475 = db.StringProperty(required = False)
    T000476 = db.StringProperty(required = False)
    U000031 = db.StringProperty(required = False)
    U000038 = db.StringProperty(required = False)
    U000039 = db.StringProperty(required = False)
    V000081 = db.StringProperty(required = False)
    V000108 = db.StringProperty(required = False)
    V000127 = db.StringProperty(required = False)
    V000128 = db.StringProperty(required = False)
    V000129 = db.StringProperty(required = False)
    V000130 = db.StringProperty(required = False)
    V000131 = db.StringProperty(required = False)
    V000132 = db.StringProperty(required = False)
    W000187 = db.StringProperty(required = False)
    W000207 = db.StringProperty(required = False)
    W000215 = db.StringProperty(required = False)
    W000413 = db.StringProperty(required = False)
    W000437 = db.StringProperty(required = False)
    W000672 = db.StringProperty(required = False)
    W000738 = db.StringProperty(required = False)
    W000779 = db.StringProperty(required = False)
    W000791 = db.StringProperty(required = False)
    W000795 = db.StringProperty(required = False)
    W000796 = db.StringProperty(required = False)
    W000797 = db.StringProperty(required = False)
    W000798 = db.StringProperty(required = False)
    W000799 = db.StringProperty(required = False)
    W000800 = db.StringProperty(required = False)
    W000802 = db.StringProperty(required = False)
    W000803 = db.StringProperty(required = False)
    W000804 = db.StringProperty(required = False)
    W000805 = db.StringProperty(required = False)
    W000806 = db.StringProperty(required = False)
    W000807 = db.StringProperty(required = False)
    W000808 = db.StringProperty(required = False)
    W000809 = db.StringProperty(required = False)
    W000810 = db.StringProperty(required = False)
    W000811 = db.StringProperty(required = False)
    W000812 = db.StringProperty(required = False)
    W000813 = db.StringProperty(required = False)
    W000814 = db.StringProperty(required = False)
    W000815 = db.StringProperty(required = False)
    W000816 = db.StringProperty(required = False)
    W000817 = db.StringProperty(required = False)
    W000818 = db.StringProperty(required = False)
    W000819 = db.StringProperty(required = False)
    W000820 = db.StringProperty(required = False)
    W000821 = db.StringProperty(required = False)
    W000822 = db.StringProperty(required = False)
    Y000031 = db.StringProperty(required = False)
    Y000033 = db.StringProperty(required = False)
    Y000062 = db.StringProperty(required = False)
    Y000063 = db.StringProperty(required = False)
    Y000064 = db.StringProperty(required = False)
    Y000065 = db.StringProperty(required = False)
    Y000066 = db.StringProperty(required = False)
    Z000017 = db.StringProperty(required = False)
    Z000018 = db.StringProperty(required = False)

class NewsLetterUser(db.Model):
    created = db.DateTimeProperty(required = True, auto_now = True)
    email = db.StringProperty(required = True)

    @classmethod
    def by_email(cls, email):
        u = cls.all().filter('email =', email).get()
        return u

class DatastoreFile(db.Model):
  data = db.BlobProperty(required=True)
  mimetype = db.StringProperty(required=True)

class NationalDemocraticPrimary(db.Model):
    pollster = db.StringProperty(required=True)
    start_date = db.DateTimeProperty(required=True)
    end_date = db.DateTimeProperty(required=True)
    entry_date = db.DateTimeProperty(required=True)
    popsize = db.IntegerProperty(required=True)
    poptype = db.StringProperty(required=True)
    mode = db.StringProperty(required=True)
    hill = db.IntegerProperty(required=False)
    sanders = db.IntegerProperty(required=False)
    omalley = db.IntegerProperty(required=False)
    chafee = db.IntegerProperty(required=False)
    webb = db.IntegerProperty(required=False)
    biden = db.IntegerProperty(required=False)
    undecided = db.IntegerProperty(required=False)
    url = db.StringProperty(required=True)

class NationalRepublicanPrimary(db.Model):
    pollster = db.StringProperty(required=True)
    start_date = db.DateTimeProperty(required=True)
    end_date = db.DateTimeProperty(required=True)
    entry_date = db.DateTimeProperty(required=True)
    popsize = db.IntegerProperty(required=True)
    poptype = db.StringProperty(required=True)
    mode = db.StringProperty(required=True)
    trump = db.IntegerProperty(required=False)
    cruz = db.IntegerProperty(required=False)
    rubio = db.IntegerProperty(required=False)
    carson = db.IntegerProperty(required=False)
    bush = db.IntegerProperty(required=False)
    christie = db.IntegerProperty(required=False)
    paul = db.IntegerProperty(required=False)
    fiorina = db.IntegerProperty(required=False)
    huckabee = db.IntegerProperty(required=False)
    kasich = db.IntegerProperty(required=False)
    santorum = db.IntegerProperty(required=False)
    gilmore = db.IntegerProperty(required=False)
    gram = db.IntegerProperty(required=False)
    jindal = db.IntegerProperty(required=False)
    pataki = db.IntegerProperty(required=False)
    perry = db.IntegerProperty(required=False)
    walker = db.IntegerProperty(required=False)
    undecided = db.IntegerProperty(required=False)
    url = db.StringProperty(required=True)

class Politician(db.Model):
    in_office = db.StringProperty(required = True)
    party = db.StringProperty(required = True)
    gender = db.StringProperty(required = True)
    state = db.StringProperty(required = True)
    state_name = db.StringProperty(required = True)
    distrank = db.StringProperty(required = True)
    chamber = db.StringProperty(required = True)
    birthday = db.StringProperty(required = True)
    fyio = db.IntegerProperty(required = True)
    bioguide_id = db.StringProperty(required = True)
    crp_id = db.StringProperty(required = True)
    fec_ids = db.StringProperty(required = True)
    name = db.StringProperty(required = True)
    phone = db.StringProperty(required = True)
    website = db.StringProperty(required = True)
    contact_form = db.StringProperty(required = True)
    twitter_id = db.StringProperty(required = True)
    youtube_id = db.StringProperty(required = True)
    facebook_id = db.StringProperty(required = True)

class Bill(db.Model):
    bill_id = db.StringProperty(required = True)
    official_title = db.StringProperty(required = True)
    popular_title = db.StringProperty(required = True)
    short_title = db.StringProperty(required = True)
    nicknames = db.StringProperty(required = True)
    url = db.StringProperty(required = True)
    active = db.StringProperty(required = True)
    vetoed = db.StringProperty(required = True)
    enacted = db.StringProperty(required = True)
    sponsor_id = db.StringProperty(required = True)
    introduced = db.DateTimeProperty(required = True)
    last_action = db.DateTimeProperty(required = True)
    last_updated = db.DateTimeProperty(required = True)

class Cosponsor(db.Model):
    bill_id = db.StringProperty(required = True)
    bioguide_id = db.StringProperty(required = True)

class Visualization(db.Model):
    name = db.StringProperty(required = True)
    vtype = db.StringProperty(required = True)
    title = db.StringProperty(required = True)
    xaxis = db.StringProperty(required = True)
    yaxis = db.StringProperty(required = True)
    element = db.StringProperty(required = True)
    query = db.StringProperty(required = True)
    color = db.StringProperty(required = True)